### ISSUE TITLE
[BUG] Config path does not seem to respect `$XDG_CONFIG_HOME` variable

### ISSUE THREAD

**Issue by lachieh** [bytecodealliance/wasm-pkg-tools#111]
From my (very sparse) testing, it doesn't look like the `wkg` config path is respecting the $XDG_CONFIG_HOME variable.

```console
$ echo "$XDG_CONFIG_HOME"
/Users/lheywood/.config

$ EDITOR=ls wkg config --edit
/Users/lheywood/Library/Application Support/wasm-pkg/config.toml
```console

**Comment by lann** [comment]
The README is mistaken for macos. The config dir is taken from this: https://docs.rs/dirs/5.0.1/dirs/fn.config_dir.html

**Comment by thomastaylor312** [comment]
The funny thing is that I copied that straight from dirs. I'm going to switch out our use of `dirs` (since it brings in a transitive MPL license anyway) for etcetera, which respects XDG config
