### ISSUE TITLE
Unified publishing

### ISSUE THREAD

**Issue by lann** [bytecodealliance/wasm-pkg-tools#13]
Currently, if you want to publish a package to a warg registry you use `warg` and if you want to publish to an OCI registry you use some OCI tool (like `oras`). For toolchain-specific tools like `cargo-component` that want to support their own `publish` flow it would be nice to have a unified publishing library available.

Supporting the full feature set of e.g. warg seems out of scope for this library, but it does seem plausible to support a subset of common operations like basic single release publishing, selecting the appropriate protocol by consulting the well-known wasm-pkg URL for the destination registry domain.

This functionality could also be exposed via an e.g. `wkg publish` subcommand.

**Comment by thomastaylor312** [comment]
This should be completed in #80
