### ISSUE TITLE
How to download a WASI spec from ghcr?

### ISSUE THREAD

**Issue by yoshuawuyts** [bytecodealliance/wasm-pkg-tools#38]
### Problem

Now that we have WASI specifications pushed as OCI to ghcr, I would like to download them using `wasm-pkg-tools`. In https://github.com/WebAssembly/WASI/issues/606#issuecomment-2159116663 @ricochet showed the following two commands to download from ghcr:

```bash
$ wasm-pkg-loader webassembly:wasi-http fetch 0.2.0
$ wasm-tools component wit webassembly-wasi-http-0.2.0.wasm tail -n 15
```

However, when I try running this locally, I get the following error:

```text
Fetching release details for webassembly:wasi-http@0.2.0...
Error: error getting release details

Caused by:
    no registry configured for namespace "webassembly"
```

I don't know how to configure a registry locally since docs seem to be missing. And there doesn't appear to be a way to override the command to point to ghcr instead. Even basic docs for how to configure a registry locally would be helpful here.

**Comment by lann** [comment]
I think the example commands must have been paired with some old tooling and local override config. Try:

```
$ cargo install wkg
...
$ wkg get wasi:http
No version specified; fetching version list...
Getting wasi:http@0.2.0...
Wrote './wasi_http@0.2.0.wit'
```

**Comment by yoshuawuyts** [comment]
I tried this today, and it worked really well. Thank you!
