### ISSUE TITLE
wasm-pkg-tools fails on help

### ISSUE THREAD

**Issue by yoshuawuyts** [bytecodealliance/wasm-pkg-tools#39]
When I run the following command:

```bash
wasm-pkg-loader --help
```

I get the following error:

```text
Error: invalid package ref format

Caused by:
    invalid package ref: missing expected ':'
```

This is likely due to `wasm-pkg-loader` not using a CLI parser package like `clap`, but instead rolling its own command parsing. I don't know what the eventual plan is for binaries in this repo, but I would encourage using CLI parser packages even for temporary tools which we eventually intend to replace. Not being able to validate I was using the `wasm-pkg-loader` correctly via `--help` was very confusing.

**Comment by thomastaylor312** [comment]
Yeah @yoshuawuyts #41 removes the loader binary so it isn't there anymore, I also have some more cleanup around wkg coming in with #33 once we finish some other PRs so I can rebase that and update based on some conversation from the packaging meeting

**Comment by yoshuawuyts** [comment]
Okay, great! Happy to close this since #41 will remove the binary entirely.
