### ISSUE TITLE
Linking SSL libraries on ubuntu 20.04

### ISSUE THREAD

**Issue by jsturtevant** [bytecodealliance/wasm-pkg-tools#75]
When running the package on ubuntu 20.04 I get:

```
./wkg
./wkg: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
```

Using Ubuntu 22 or 24, works since it comes with ssl 3.0. Manually upgrading to ssl 3.0 also works but since the Ununtu package manager doesn't come with it by default and 20.04 isn't EOL until April 2025 might want to either document. static linking or have a fallback.

Not a huge deal just thought I would document the error here

**Comment by thomastaylor312** [comment]
@jsturtevant Did you build from source or download from elsewhere? 

Either way, we should probably make sure we're using rustls everywhere so we don't run into this problem

**Comment by jsturtevant** [comment]
I downloaded it from the release: https://github.com/bytecodealliance/wasm-pkg-tools/releases

**Comment by thomastaylor312** [comment]
Ok, I'll try to roll in a fix on my next PR

**Comment by calvinrp** [comment]
@thomastaylor312 When you are looking into it... The binary artifacts are built with `cargo binstall` support in mind. The relevant files:

https://github.com/bytecodealliance/wasm-pkg-tools/blob/main/Cross.toml
https://github.com/bytecodealliance/wasm-pkg-tools/blob/main/.github/workflows/publish-binaries.yml

Could change just for the CI binary artifacts or for the source builds. I don't have preferences.

**Comment by thomastaylor312** [comment]
So I have mostly done this, but it turns out the warg-client doesn't have the option to enable rustls. We'll need to add that there to fully enable it

**Comment by thomastaylor312** [comment]
@jsturtevant this should be fixed on latest main:

```
cargo tree | rg -i tls
│   │   ├── hyper-rustls v0.27.2
│   │   │   ├── rustls v0.23.12
│   │   │   │   ├── rustls-pki-types v1.8.0
│   │   │   │   ├── rustls-webpki v0.102.7
│   │   │   │   │   ├── rustls-pki-types v1.8.0
│   │   │   ├── rustls-pki-types v1.8.0
│   │   │   ├── tokio-rustls v0.26.0
│   │   │   │   ├── rustls v0.23.12 (*)
│   │   │   │   ├── rustls-pki-types v1.8.0
│   │   │       └── rustls-pki-types v1.8.0
│   │   ├── rustls v0.23.12 (*)
│   │   ├── rustls-pemfile v2.1.3
│   │   │   └── rustls-pki-types v1.8.0
│   │   ├── rustls-pki-types v1.8.0
│   │   ├── tokio-rustls v0.26.0 (*)
```

As you can see, no native tls stuff. Let me know if you have any more problems
