### ISSUE TITLE
Change `wasm-pkg-loader` global config path

### ISSUE THREAD

**Issue by lann** [bytecodealliance/wasm-pkg-tools#8]
As `wasm-pkg-loader` was renamed from `warg-loader`, its global config path should probably change from `<user config>/warg/config.toml` to something more protocol-agnostic. This leads to one of the Hard Problems of Software Engineering: naming things.

**Comment by lann** [comment]
I guess a default starting point should probably be the most boring/obvious: `/wasm-pkg/config.toml`

We have also discussed supporting [hierarchical config like `cargo` does](https://doc.rust-lang.org/cargo/reference/config.html#hierarchical-structure), which would suggest e.g. `project/.wasm-pkg/config.toml`

**Comment by calvinrp** [comment]
Rename `<user config>/wasm-pkg/config.toml` makes sense
